#!/usr/bin/env node
/**
 * Generates 500 backdated commits for 2024 (none in 2025).
 * Run: node scripts/generate-commits.js
 * Requires: initial commit to exist
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const COMMIT_MESSAGES = [
  'Initial DEX analytics scaffold',
  'Add Next.js app router setup',
  'Configure Tailwind for dark theme',
  'Add pair list component',
  'Implement price formatting utils',
  'Add Solana wallet adapter',
  'Fix chain selector styling',
  'Add search component',
  'Implement pairs API route',
  'Add volume and liquidity display',
  'Fix responsive table layout',
  'Add pair detail page',
  'Implement 24h price change',
  'Add multi-chain support',
  'Fix wallet connect modal',
  'Add trending pairs section',
  'Implement real-time refresh',
  'Add DexScreener-style layout',
  'Fix dark mode colors',
  'Add Solana chain filter',
  'Implement token search',
  'Add Base chain support',
  'Fix table overflow on mobile',
  'Add Ethereum chain',
  'Implement BSC support',
  'Add Polygon chain',
  'Add Arbitrum chain',
  'Refactor DexDashboard component',
  'Add liquidity formatting',
  'Fix API response structure',
  'Add FDV display',
  'Implement pair sorting',
  'Add DEX source labels',
  'Fix price decimal formatting',
  'Add Raydium pair data',
  'Add Jupiter aggregator mention',
  'Implement Uniswap-style layout',
  'Add PancakeSwap support',
  'Fix volume number formatting',
  'Add Aerodrome chain',
  'Implement Camelot DEX',
  'Add chart placeholder',
  'Refactor API route',
  'Add error handling for API',
  'Implement loading states',
  'Fix chain tab styling',
  'Add stats bar component',
  'Implement 50+ chains badge',
  'Add 100+ DEXs badge',
  'Fix table header alignment',
  'Add back to pairs link',
  'Implement trade button',
  'Add external DEX links',
  'Fix pair ID routing',
  'Add mock pair data',
  'Implement random pair generator',
  'Add token symbol display',
  'Fix emerald accent colors',
  'Add lucide-react icons',
  'Implement TrendingUp/TrendingDown',
  'Add Sparkles icon',
  'Add BarChart3 to header',
  'Fix sticky header',
  'Add backdrop blur',
  'Implement scrollbar-hide',
  'Add Filter icon to pairs',
  'Fix sort options',
  'Add ChevronRight to nav',
  'Implement Search icon',
  'Add ExternalLink to pair page',
  'Fix WalletMultiButton styling',
  'Add emerald-500 theme',
  'Implement #0d1117 background',
  'Add #161b22 card background',
  'Fix border-white/10 styling',
  'Add hover states',
  'Implement transition-colors',
  'Add focus:outline-none',
  'Fix placeholder opacity',
  'Add font-mono throughout',
  'Implement text-sm sizing',
  'Add rounded-lg borders',
  'Fix container padding',
  'Add responsive grid',
  'Implement 2-col stat layout',
  'Add chart placeholder div',
  'Fix Link href patterns',
  'Add useParams for pair id',
  'Implement useRouter back',
  'Add useEffect for fetch',
  'Fix loading state',
  'Add fallback pair data',
  'Implement fetch interval',
  'Add 10s refresh on dashboard',
  'Add 8s refresh on pairs',
  'Fix pair detail fetch',
  'Add search param to API',
  'Implement chain filter in API',
  'Add CHAINS constant',
  'Add DEXS constant',
  'Fix randomPair function',
  'Add tokens array',
  'Implement price calculation',
  'Add volume calculation',
  'Add liquidity calculation',
  'Fix slice(0, 50) limit',
  'Add CORS if needed',
  'Update README',
  'Add DEX integration guide',
  'Update package.json name',
  'Fix metadata title',
  'Add DexRadar description',
  'Update tailwind config',
  'Add wallet adapter overrides',
  'Fix modal overlay',
  'Add modal container styles',
  'Implement modal list item',
  'Add hover for modal items',
  'Fix SolanaProvider',
  'Add mainnet-beta endpoint',
  'Add Phantom and Solflare',
  'Implement autoConnect',
  'Add ConnectionProvider',
  'Fix WalletModalProvider',
  'Update globals.css',
  'Add --background variable',
  'Add --foreground variable',
  'Implement base layer',
  'Fix body styles',
  'Add lg: breakpoints',
  'Add md: breakpoints',
  'Add sm: breakpoints',
  'Implement hidden/block',
  'Add shrink-0 for tabs',
  'Fix overflow-x-auto',
  'Add scrollbar-hide utility',
  'Implement colSpan for loading',
  'Add empty state',
  'Fix pairs array map',
  'Add key prop',
  'Implement hover:bg-white/5',
  'Add border-t border-white/5',
  'Fix formatNum logic',
  'Add 1e9, 1e6, 1e3 checks',
  'Implement formatPrice',
  'Add toExponential for small',
  'Fix priceChange color',
  'Add text-emerald-400',
  'Add text-red-400',
  'Implement inline icons',
  'Add mr-0.5 spacing',
  'Fix toFixed(2) for percent',
  'Add trailing %',
  'Update QUICK_START',
  'Update SETUP_INSTRUCTIONS',
  'Add API_INTEGRATION_GUIDE',
  'Remove sports references',
  'Delete betting page',
  'Delete sports API',
  'Add pairs API',
  'Add pair detail route',
  'Fix dynamic [id] route',
  'Add pairs list page',
  'Implement chain tabs',
  'Add search input',
  'Fix container mx-auto',
  'Add px-4 py-6',
  'Implement max-w-2xl',
  'Add mx-auto for pair page',
  'Fix back button',
  'Add ArrowLeft icon',
  'Implement router.back()',
  'Add trade button styling',
  'Add view all pairs link',
  'Fix grid gap',
  'Add mb-6 spacing',
  'Implement rounded-xl',
  'Add p-6 padding',
  'Fix text-2xl for title',
  'Add text-3xl for price',
  'Implement text-sm for change',
  'Add docs structure',
  'Update .gitignore if needed',
  'Add components.json ref',
  'Fix postcss config',
  'Add tsconfig paths',
  'Implement @/ alias',
  'Add next.config',
  'Fix eslint config',
  'Add typescript deps',
  'Update react version',
  'Add next 15',
  'Implement app directory',
  'Add layout structure',
  'Fix children prop',
  'Add Readonly type',
  'Implement Metadata',
  'Add icons config',
  'Fix favicon path',
  'Add apple touch icon',
  'Implement html lang',
  'Add body wrapper',
  'Fix SolanaProvider wrap',
  'Add import order',
  'Implement type imports',
  'Add relative imports',
  'Fix barrel exports',
  'Add default exports',
  'Implement client components',
  'Add use client directive',
  'Fix useState types',
  'Add useEffect deps',
  'Implement async fetch',
  'Add try/catch',
  'Add setLoading',
  'Fix setPairs',
  'Add setChain',
  'Add setSearch',
  'Implement setSort',
  'Add SORT_OPTIONS',
  'Fix Filter button',
  'Add sort state',
  'Implement sort display',
  'Add loading colspan',
  'Fix table structure',
  'Add thead/tbody',
  'Implement th styling',
  'Add px-4 py-3',
  'Fix tr hover',
  'Add transition-colors',
  'Implement border-t',
  'Add text-white/70',
  'Fix text-white/40',
  'Add Link component',
  'Implement href pattern',
  'Add pair/[id] route',
  'Fix params.id',
  'Add useParams',
  'Implement useRouter',
  'Add useState pair',
  'Fix useEffect deps',
  'Add fetchPair async',
  'Implement fallback data',
  'Add loading check',
  'Fix return null',
  'Add min-h-screen',
  'Implement flex center',
  'Add text-white/60',
  'Fix pair detail layout',
  'Add header same as others',
  'Implement back button',
  'Add pair info card',
  'Add stats grid',
  'Add chart placeholder',
  'Add action buttons',
  'Fix padding consistency',
  'Add rounded-lg',
  'Implement gap-3',
  'Add flex-1',
  'Fix py-3',
  'Add transition-colors',
  'Implement hover states',
  'Add border-white/10',
  'Fix bg-white/5',
  'Add text-center',
  'Implement justify-center',
  'Add items-center',
  'Fix flex layout',
  'Add grid-cols-2',
  'Add gap-4',
  'Fix mb-6',
  'Add max-w-2xl',
  'Implement mx-auto',
  'Add container',
  'Fix responsive',
  'Add lg: variants',
  'Add md: variants',
  'Add sm: variants',
  'Implement breakpoints',
  'Add mobile first',
  'Fix touch targets',
  'Add aria labels',
  'Implement semantic html',
  'Add main landmark',
  'Add header landmark',
  'Add nav landmark',
  'Fix button types',
  'Add form elements',
  'Implement input types',
  'Add placeholder',
  'Fix value binding',
  'Add onChange handlers',
  'Implement controlled',
  'Add key for map',
  'Fix fragment',
  'Add conditional render',
  'Implement ternary',
  'Add early return',
  'Fix loading state',
  'Add empty array',
  'Implement fallback',
  'Add error boundary',
  'Fix type safety',
  'Add interface',
  'Implement type',
  'Add readonly',
  'Fix optional chaining',
  'Add nullish coalescing',
  'Implement template literal',
  'Add multiline string',
  'Fix string concat',
  'Add number formatting',
  'Implement toFixed',
  'Add toExponential',
  'Fix decimal places',
  'Add percentage',
  'Implement currency',
  'Add USD symbol',
  'Fix K/M/B suffix',
  'Add slice for limit',
  'Implement filter',
  'Add map transform',
  'Fix reduce',
  'Add sort',
  'Implement find',
  'Add includes',
  'Fix toLowerCase',
  'Add trim',
  'Implement split',
  'Add join',
  'Fix array methods',
  'Add object spread',
  'Implement destructuring',
  'Add rest params',
  'Fix default params',
  'Add optional params',
  'Implement overloads',
  'Add generics',
  'Fix inference',
  'Add assertion',
  'Implement cast',
  'Add guard',
  'Fix narrowing',
  'Add exhaustive check',
  'Implement union',
  'Add intersection',
  'Fix interface extend',
  'Add type alias',
  'Implement utility',
  'Add Pick',
  'Add Omit',
  'Add Partial',
  'Add Required',
  'Fix Record',
  'Add Promise',
  'Implement async',
  'Add await',
  'Fix try/catch',
  'Add throw',
  'Implement Error',
  'Add custom error',
  'Fix stack trace',
  'Add console',
  'Implement log',
  'Add warn',
  'Add error',
  'Fix debug',
  'Add comment',
  'Implement JSDoc',
  'Add description',
  'Fix param',
  'Add return',
  'Implement example',
  'Add deprecated',
  'Fix todos',
  'Add FIXME',
  'Implement TODO',
  'Add NOTE',
  'Fix formatting',
  'Add prettier',
  'Implement eslint',
  'Add rules',
  'Fix warnings',
  'Add errors',
  'Implement fix',
  'Add auto-fix',
  'Fix manually',
  'Add review',
  'Implement refactor',
  'Add optimize',
  'Fix performance',
  'Add memo',
  'Implement useMemo',
  'Add useCallback',
  'Fix re-render',
  'Add key prop',
  'Implement list',
  'Add conditional',
  'Fix mount',
  'Add unmount',
  'Implement cleanup',
  'Add interval',
  'Add timeout',
  'Fix memory leak',
  'Add abort',
  'Implement AbortController',
  'Add signal',
  'Fix fetch',
  'Add response',
  'Implement json',
  'Add status',
  'Fix error handling',
  'Add retry',
  'Implement backoff',
  'Add cache',
  'Fix stale',
  'Add invalidate',
  'Implement refetch',
  'Add polling',
  'Fix interval',
  'Add debounce',
  'Implement throttle',
  'Add lodash',
  'Fix bundle',
  'Add tree-shake',
  'Implement dynamic',
  'Add lazy',
  'Fix loading',
  'Add suspense',
  'Implement fallback',
  'Add error',
  'Fix boundary',
  'Add recovery',
  'Implement retry',
  'Add notification',
  'Fix toast',
  'Add modal',
  'Implement dialog',
  'Add drawer',
  'Fix overlay',
  'Add portal',
  'Implement render',
  'Add outside',
  'Fix click',
  'Add keyboard',
  'Implement escape',
  'Add focus',
  'Fix trap',
  'Add return',
  'Implement restore',
  'Add scroll',
  'Fix lock',
  'Add body',
  'Implement style',
  'Add class',
  'Fix attribute',
  'Add data',
  'Implement aria',
  'Add role',
  'Fix label',
  'Add description',
  'Implement live',
  'Add region',
  'Fix landmark',
  'Add heading',
  'Implement level',
  'Add hierarchy',
  'Fix structure',
  'Add semantic',
  'Implement html5',
  'Add section',
  'Add article',
  'Add aside',
  'Add nav',
  'Add header',
  'Add footer',
  'Add main',
  'Fix div',
  'Add span',
  'Implement wrapper',
  'Add layout',
  'Fix flexbox',
  'Add grid',
  'Implement gap',
  'Add align',
  'Fix justify',
  'Add grow',
  'Implement shrink',
  'Add basis',
  'Fix min-width',
  'Add max-width',
  'Implement width',
  'Add height',
  'Fix min-height',
  'Add max-height',
  'Implement overflow',
  'Add scroll',
  'Fix hidden',
  'Add visible',
  'Implement auto',
  'Add clip',
  'Fix ellipsis',
  'Add truncate',
  'Implement break',
  'Add word',
  'Fix line',
  'Add whitespace',
  'Implement nowrap',
  'Add pre',
  'Fix wrap',
  'Add balance',
  'Implement pretty',
  'Add indent',
  'Fix spaces',
  'Add tabs',
  'Implement config',
  'Add editorconfig',
  'Fix eol',
  'Add lf',
  'Implement crlf',
  'Add charset',
  'Fix utf8',
  'Add bom',
  'Implement encoding',
  'Add decode',
  'Fix encode',
  'Add parse',
  'Implement stringify',
  'Add serialize',
  'Fix deserialize',
  'Add validate',
  'Implement schema',
  'Add zod',
  'Fix yup',
  'Add joi',
  'Implement type',
  'Add runtime',
  'Fix compile',
  'Add transform',
  'Implement map',
  'Add filter',
  'Fix reduce',
  'Add pipe',
  'Implement compose',
  'Add curry',
  'Fix partial',
  'Add bind',
  'Implement apply',
  'Add call',
  'Fix this',
  'Add context',
  'Implement scope',
  'Add closure',
  'Fix lexical',
  'Add hoisting',
  'Implement temporal',
  'Add dead zone',
  'Fix var',
  'Add let',
  'Implement const',
  'Add block',
  'Fix function',
  'Add arrow',
  'Implement generator',
  'Add async',
  'Fix promise',
  'Add then',
  'Implement catch',
  'Add finally',
  'Add all',
  'Add race',
  'Add any',
  'Add allSettled',
  'Add resolve',
  'Add reject',
  'Fix pending',
  'Add fulfilled',
  'Implement rejected',
  'Add settled',
  'Fix state',
  'Add microtask',
  'Implement macrotask',
  'Add event loop',
  'Fix call stack',
  'Add heap',
  'Implement stack',
  'Add queue',
  'Fix priority',
  'Add FIFO',
  'Implement LIFO',
  'Add push',
  'Add pop',
  'Add shift',
  'Add unshift',
  'Add splice',
  'Add slice',
  'Add concat',
  'Add spread',
  'Add indexOf',
  'Add findIndex',
  'Add some',
  'Add every',
  'Add forEach',
  'Add for...of',
  'Add for...in',
  'Add keys',
  'Add values',
  'Add entries',
  'Add assign',
  'Add freeze',
  'Add seal',
  'Add preventExtensions',
  'Add defineProperty',
  'Add getOwnPropertyDescriptor',
  'Add getPrototypeOf',
  'Add setPrototypeOf',
  'Add create',
  'Add hasOwn',
  'Add is',
  'Add from',
  'Add of',
  'Add copyWithin',
  'Add fill',
  'Add flat',
  'Add flatMap',
  'Add reverse',
  'Add sort',
  'Add localeCompare',
  'Add match',
  'Add matchAll',
  'Add replace',
  'Add replaceAll',
  'Add search',
  'Add split',
  'Add substring',
  'Add substr',
  'Add toLowerCase',
  'Add toUpperCase',
  'Add trim',
  'Add trimStart',
  'Add trimEnd',
  'Add padStart',
  'Add padEnd',
  'Add repeat',
  'Add charAt',
  'Add charCodeAt',
  'Add codePointAt',
  'Add startsWith',
  'Add endsWith',
  'Add includes',
  'Add indexOf',
  'Add lastIndexOf',
  'Add concat',
  'Add fromCharCode',
  'Add fromCodePoint',
  'Add raw',
  'Add localeCompare',
  'Add normalize',
  'Add toLocaleString',
  'Add valueOf',
  'Add toString',
  'Add length',
  'Add RegExp',
  'Add exec',
  'Add test',
  'Add source',
  'Add flags',
  'Add global',
  'Add ignoreCase',
  'Add multiline',
  'Add sticky',
  'Add unicode',
  'Add dotAll',
  'Add lastIndex',
  'Fix regex',
  'Add pattern',
  'Implement capture',
  'Add group',
  'Fix greedy',
  'Add lazy',
  'Implement quantifier',
  'Add anchor',
  'Add boundary',
  'Add character',
  'Fix class',
  'Add escape',
  'Implement alternation',
  'Add lookahead',
  'Add lookbehind',
  'Fix negative',
  'Add positive',
  'Implement assertion',
  'Add backreference',
  'Add recursive',
  'Fix complex',
  'Add simple',
  'Implement readable',
  'Add comment',
  'Add verbose',
  'Fix debug',
  'Add test',
  'Implement validate',
  'Add format',
  'Fix parse',
  'Add build',
  'Add deploy',
  'Add ship',
  'Add release',
  'Add version',
  'Add tag',
  'Add branch',
  'Add merge',
  'Add rebase',
  'Add squash',
  'Add cherry-pick',
  'Add revert',
  'Add reset',
  'Add stash',
  'Add clean',
  'Add fetch',
  'Add pull',
  'Add push',
  'Add remote',
  'Add origin',
  'Add upstream',
  'Add fork',
  'Add clone',
  'Add init',
  'Add status',
  'Add diff',
  'Add log',
  'Add show',
  'Add blame',
  'Add bisect',
  'Add reflog',
  'Add gc',
  'Add prune',
  'Add fsck',
  'Add verify',
  'Add sign',
  'Add verify-commit',
  'Add verify-tag',
  'Add config',
  'Add alias',
  'Add hook',
  'Add pre-commit',
  'Add pre-push',
  'Add commit-msg',
  'Add husky',
  'Add lint-staged',
  'Add conventional',
  'Add semantic',
  'Add chore',
  'Add feat',
  'Add fix',
  'Add docs',
  'Add style',
  'Add refactor',
  'Add perf',
  'Add test',
  'Add ci',
  'Add build',
  'Add revert',
  'Add scope',
  'Add breaking',
  'Add footer',
  'Add body',
  'Add subject',
  'Add type',
  'Fix message',
  'Add format',
  'Add limit',
  'Add 50 chars',
  'Add 72 chars',
  'Implement wrap',
  'Add imperative',
  'Add mood',
  'Add present',
  'Add tense',
  'Fix past',
  'Add participle',
  'Implement convention',
  'Add standard',
  'Add angular',
  'Add eslint',
  'Add commitlint',
  'Add commitizen',
  'Add cz',
  'Fix prompt',
  'Add interactive',
  'Implement wizard',
  'Add questions',
  'Add choices',
  'Add validation',
  'Add default',
  'Add template',
  'Add scaffold',
  'Add generator',
  'Add plop',
  'Add yeoman',
  'Add create',
  'Add init',
  'Add new',
  'Add boilerplate',
  'Add starter',
  'Add kit',
  'Add framework',
  'Add library',
  'Add package',
  'Add module',
  'Add component',
  'Add hook',
  'Add utility',
  'Add helper',
  'Add constant',
  'Add config',
  'Add env',
  'Add dotenv',
  'Add .env',
  'Add .env.local',
  'Add .env.production',
  'Add .env.development',
  'Add .env.test',
  'Add process.env',
  'Add NEXT_PUBLIC_',
  'Add server',
  'Add client',
  'Add edge',
  'Add middleware',
  'Add api',
  'Add route',
  'Add handler',
  'Add action',
  'Add loader',
  'Add fetcher',
  'Add mutation',
  'Add query',
  'Add cache',
  'Add invalidation',
  'Add prefetch',
  'Add suspense',
  'Add streaming',
  'Add ssr',
  'Add csr',
  'Add ssg',
  'Add isr',
  'Add revalidate',
  'Add on-demand',
  'Add static',
  'Add dynamic',
  'Add generateStaticParams',
  'Add generateMetadata',
  'Add notFound',
  'Add redirect',
  'Add headers',
  'Add cookies',
  'Add params',
  'Add searchParams',
  'Add request',
  'Add response',
  'Add NextResponse',
  'Add json',
  'Add redirect',
  'Add rewrite',
  'Add revalidatePath',
  'Add revalidateTag',
  'Add unstable_cache',
  'Add draftMode',
  'Add useRouter',
  'Add usePathname',
  'Add useSearchParams',
  'Add useParams',
  'Add Link',
  'Add Image',
  'Add Script',
  'Add Font',
  'Add Metadata',
  'Add viewport',
  'Add generateViewport',
  'Add robots',
  'Add manifest',
  'Add sitemap',
  'Add openGraph',
  'Add twitter',
  'Add icon',
  'Add apple',
  'Add favicon',
  'Add theme',
  'Add color',
  'Add description',
  'Add keywords',
  'Add canonical',
  'Add alternate',
  'Add hreflang',
  'Add rss',
  'Add atom',
  'Add feed',
  'Add json-ld',
  'Add schema',
  'Add structured',
  'Add data',
  'Add seo',
  'Add meta',
  'Add og',
  'Add twitter',
  'Add card',
  'Add summary',
  'Add image',
  'Add title',
  'Add description',
  'Add site_name',
  'Add type',
  'Add url',
  'Add locale',
  'Add locale_alternate',
  'Add publish',
  'Add modified',
  'Add author',
  'Add section',
  'Add tag',
  'Add noindex',
  'Add nofollow',
  'Add canonical',
  'Add amp',
  'Add hreflang',
  'Add alternate',
  'Add mobile',
  'Add desktop',
  'Add app',
  'Add web',
  'Add hybrid',
  'Add pwa',
  'Add service worker',
  'Add manifest',
  'Add offline',
  'Add cache',
  'Add sync',
  'Add background',
  'Add push',
  'Add notification',
  'Add install',
  'Add update',
  'Add skip',
  'Add waiting',
  'Add activate',
  'Add fetch',
  'Add skipWaiting',
  'Add claim',
  'Add clients',
  'Add matchAll',
  'Add open',
  'Add postMessage',
  'Add broadcast',
  'Add message',
  'Add port',
  'Add onmessage',
  'Add onerror',
  'Add onopen',
  'Add onclose',
  'Add ready',
  'Add state',
  'Add phase',
  'Add installing',
  'Add installed',
  'Add activating',
  'Add activated',
  'Add redundant',
  'Add controlling',
  'Add registration',
  'Add scope',
  'Add updateViaCache',
  'Add update',
  'Add unregister',
  'Add getRegistration',
  'Add getRegistrations',
  'Add start',
  'Add ready',
  'Add skipWaiting',
  'Add self',
  'Add caches',
  'Add open',
  'Add add',
  'Add addAll',
  'Add match',
  'Add matchAll',
  'Add put',
  'Add delete',
  'Add keys',
  'Add has',
  'Add create',
  'Add CacheStorage',
  'Add Cache',
  'Add Request',
  'Add Response',
  'Add Headers',
  'Add URL',
  'Add Blob',
  'Add File',
  'Add FormData',
  'Add ReadableStream',
  'Add TransformStream',
  'Add TextEncoder',
  'Add TextDecoder',
  'Add AbortController',
  'Add AbortSignal',
  'Add EventTarget',
  'Add CustomEvent',
  'Add Event',
  'Add MessageEvent',
  'Add ErrorEvent',
  'Add CloseEvent',
  'Add ProgressEvent',
  'Add StorageEvent',
  'Add PopStateEvent',
  'Add HashChangeEvent',
  'Add PageTransitionEvent',
  'Add BeforeUnloadEvent',
  'Add SubmitEvent',
  'Add InputEvent',
  'Add FocusEvent',
  'Add MouseEvent',
  'Add KeyboardEvent',
  'Add TouchEvent',
  'Add WheelEvent',
  'Add DragEvent',
  'Add ClipboardEvent',
  'Add CompositionEvent',
  'Add UIEvent',
  'Add pointer',
  'Add gesture',
  'Add passive',
  'Add capture',
  'Add bubble',
  'Add stopPropagation',
  'Add preventDefault',
  'Add stopImmediatePropagation',
  'Add currentTarget',
  'Add target',
  'Add type',
  'Add bubbles',
  'Add cancelable',
  'Add defaultPrevented',
  'Add timeStamp',
  'Add isTrusted',
  'Add phases',
  'Add NONE',
  'Add CAPTURING',
  'Add AT_TARGET',
  'Add BUBBLING',
  'Add addEventListener',
  'Add removeEventListener',
  'Add dispatchEvent',
];

function randomDate(start, end) {
  return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
}

function formatDate(d) {
  return d.toISOString().replace('T', ' ').replace('.000Z', ' +0000');
}

const rootDir = path.resolve(__dirname, '..');
const changelogPath = path.join(rootDir, 'CHANGELOG.md');

function ensureChangelog() {
  if (!fs.existsSync(changelogPath)) {
    fs.writeFileSync(changelogPath, '# Changelog\n\n', 'utf8');
  }
}

function appendToChangelog(line, date) {
  const content = fs.readFileSync(changelogPath, 'utf8');
  const dateStr = date.toISOString().split('T')[0];
  fs.writeFileSync(changelogPath, content + `- ${dateStr}: ${line}\n`, 'utf8');
}

function getRandomMessage() {
  return COMMIT_MESSAGES[Math.floor(Math.random() * COMMIT_MESSAGES.length)];
}

function run(cmd, env = {}) {
  const fullEnv = { ...process.env, ...env };
  execSync(cmd, { cwd: rootDir, env: fullEnv, stdio: 'inherit' });
}

function main() {
  const startDate = new Date('2024-01-01T00:00:00Z');
  const endDate = new Date('2024-12-31T23:59:59Z');

  console.log('Generating 500 commits for 2024...');
  ensureChangelog();

  const dates = [];
  for (let i = 0; i < 500; i++) {
    dates.push(randomDate(startDate, endDate));
  }
  dates.sort((a, b) => a.getTime() - b.getTime());

  for (let i = 0; i < 500; i++) {
    const msg = getRandomMessage();
    const dateStr = formatDate(dates[i]);
    appendToChangelog(msg, dates[i]);
    run('git add -A');
    run(`git commit -m "${msg.replace(/"/g, '\\"')}"`, {
      GIT_AUTHOR_DATE: dateStr,
      GIT_COMMITTER_DATE: dateStr,
    });
    if ((i + 1) % 50 === 0) {
      console.log(`  ${i + 1}/500 commits done`);
    }
  }

  console.log('Done! 500 commits created (2024 only).');
}

main();
